### PR TITLE
Features branch

### PR DESCRIPTION
**Pull request by nurislam-ab**
A clone of the Newsweek website homepage built using HTML, CSS, JS, and Bootstrap.

Bootstrap CSS classes were used widely to apply styles and also several media querie break points were applied on not to break on smaller screens.

### CODE REVIEW

**Review by imhta — CHANGES_REQUESTED** [review]
# Changes required 🛑 

### Hello  @nurislam-ab  , 👋 You have done a great job in UI👏  Still there are few things to fix

- [x] Git ignore .vscode file
**Original**

image

**Your**

image

- [x] in 666px most of the ui elements is not similar  with original  check everything, fix it


#### In 412px

**Yours** 

- [x] Can't find burger menu

image

- [x] In same width nav is breaking

image

----
### Don't forgot to request for another code review
----
**Pon Muthu Selvam N**
__nponmuthuselvam@gmail.com__
_If you have any queries, feel free to ping me on slack _

**Comment by nurislam-ab** [comment]
1. 
image

2. 
image
3. 
image

**Comment by shshamim63** [comment]
## Status :recycle: [!! Approved !!] :recycle: 
___
Hi @nurislam-ab :wave: ,
Well done :clap: , I can see all the items that are actually needed to decorate the page. Nothing is blocking me to declare this project as complete.
___
### :clubs: [Optional Changes] :clubs: 
1. _Navbar_
..1. **Large Screen** -> While the page loads i can see the hamburger icon on the nav section.
image
___
### This :+1: is from me. You can merge it.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/) | [Slack](Shakhawat Hossain)

**Comment by nurislam-ab** [comment]
> Navbar
> ..1. Large Screen -> While the page loads i can see the hamburger icon on the nav section.

tried to fix this also

**Pull request merged**
